### ISSUE TITLE
[Bug]: Error executing callback cfg_denoiser_callback

### ISSUE THREAD

**Issue by murgleburgle** [continue-revolution/sd-forge-animatediff#5]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I'm on a fresh install of ForgeUI. I've tried reinstalling forge animatediff. I've updated ForgeUI. Only the built-in controlnet extension is installed. Both animatediff and controlnet work as intended on their own. When attempting to run a vid2vid generation in ForgeUI, the following error messages are given, and no gif is created, only the batch of individual frames.

Error printed for each sampling step:
** Error executing callback cfg_denoiser_callback for C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\ForgeUI\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

Error message printed when finished sampling:
*** Error running postprocess_batch_list: C:\ForgeUI\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\ForgeUI\webui\modules\scripts.py", line 859, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\ForgeUI\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\ForgeUI\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 561, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
*** Error running postprocess_batch_list: C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\ForgeUI\webui\modules\scripts.py", line 859, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff.py", line 79, in postprocess_batch_list
        params.prompt_scheduler.save_infotext_img(p)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'

---
*** Error running postprocess: C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\ForgeUI\webui\modules\scripts.py", line 843, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff.py", line 84, in postprocess
        params.prompt_scheduler.save_infotext_txt(res)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

It should have generated a gif with controlnet input

### Commit where the problem happens

webui: version: [f0.0.14v1.8.0rc-latest-184-g43c9e3b5](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/43c9e3b5ce1642073c7a9684e36b45489eeb4a49)
extension: c25a46d3

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Error printed for each sampling step:
** Error executing callback cfg_denoiser_callback for C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\ForgeUI\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

Error message printed when finished sampling:
*** Error running postprocess_batch_list: C:\ForgeUI\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\ForgeUI\webui\modules\scripts.py", line 859, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\ForgeUI\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\ForgeUI\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 561, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
*** Error running postprocess_batch_list: C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\ForgeUI\webui\modules\scripts.py", line 859, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff.py", line 79, in postprocess_batch_list
        params.prompt_scheduler.save_infotext_img(p)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'

---
*** Error running postprocess: C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\ForgeUI\webui\modules\scripts.py", line 843, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\ForgeUI\webui\extensions\sd-forge-animatediff\scripts\animatediff.py", line 84, in postprocess
        params.prompt_scheduler.save_infotext_txt(res)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'
```

**Comment by captainzero93** [comment]
I have the same error

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.14v1.8.0rc-latest-184-g43c9e3b5
Commit hash: 43c9e3b5ce1642073c7a9684e36b45489eeb4a49
Launching Web UI with arguments:
Total VRAM 12287 MB, total RAM 32678 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
ControlNet preprocessor location: B:\2024AI\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
[-] ADetailer initialized. version: 24.1.2, num models: 9
Loading weights [c657ee88a7] from B:\2024AI\webui_forge_cu121_torch21\webui\models\Stable-diffusion\0.7(zavychromaxl_v40) + 0.3(copaxTimelessxlSDXL1_v9).safetensors
2024-02-20 21:05:36,817 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 18.8s (prepare environment: 3.8s, import torch: 5.1s, import gradio: 1.5s, setup paths: 1.3s, initialize shared: 0.2s, other imports: 1.0s, load scripts: 4.1s, create ui: 0.8s, gradio launch: 0.9s).
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Loading VAE weights specified in settings: B:\2024AI\webui_forge_cu121_torch21\webui\models\VAE\sdxl_vae_fp16fix.safetensors
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.35 seconds
Model loaded in 13.2s (load weights from disk: 1.1s, forge instantiate config: 1.9s, forge load real models: 8.9s, load VAE: 0.5s, calculate empty prompt: 0.7s).
2024-02-20 21:07:08,502 - AnimateDiff - INFO - AnimateDiff process start.
2024-02-20 21:07:08,502 - AnimateDiff - INFO - Loading motion module hsxl_temporal_layers.safetensors from B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\model\hsxl_temporal_layers.safetensors
*** Error running before_process: B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\scripts.py", line 795, in before_process
        script.before_process(p, *script_args)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py", line 56, in before_process
        motion_module.load(params.model)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 44, in load
        model_type = MotionModuleType.get_mm_type(mm_state_dict)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\motion_module.py", line 33, in get_mm_type
        if 32 in next((state_dict[key] for key in state_dict if 'pe' in key), None).shape:
    AttributeError: 'NoneType' object has no attribute 'shape'

---
2024-02-20 21:07:08,635 - AnimateDiff - INFO - Setting DDIM alpha.
*** Error running process_batch: B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\scripts.py", line 827, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py", line 69, in process_batch
        motion_module.set_ddim_alpha(p.sd_model)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 133, in set_ddim_alpha
        beta_end = 0.020 if self.mm.is_adxl else 0.012
    AttributeError: 'NoneType' object has no attribute 'is_adxl'

---
*** Error running process_before_every_sampling: B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py", line 74, in process_before_every_sampling
        motion_module.inject(p.sd_model, params.model)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 57, in inject
        assert sd_model.is_sdxl == self.mm.is_xl, f"Motion module incompatible with SD. You are using {sd_ver} with {self.mm.mm_type}."
    AttributeError: 'NoneType' object has no attribute 'is_xl'

---
To load target model SDXL
Begin to load 1 model
Moving model(s) has taken 0.90 seconds
  0%|                                                                                           | 0/30 [00:00<?, ?it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
  3%|██▊                                                                                | 1/30 [00:00<00:23,  1.26it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
  7%|█████▌                                                                             | 2/30 [00:01<00:14,  1.96it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 10%|████████▎                                                                          | 3/30 [00:01<00:11,  2.40it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 13%|███████████                                                                        | 4/30 [00:01<00:09,  2.69it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 17%|█████████████▊                                                                     | 5/30 [00:02<00:08,  2.87it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 20%|████████████████▌                                                                  | 6/30 [00:02<00:08,  3.00it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 23%|███████████████████▎                                                               | 7/30 [00:02<00:07,  3.08it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 27%|██████████████████████▏                                                            | 8/30 [00:02<00:07,  3.10it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 30%|████████████████████████▉                                                          | 9/30 [00:03<00:06,  3.16it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 33%|███████████████████████████▎                                                      | 10/30 [00:03<00:06,  3.19it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 37%|██████████████████████████████                                                    | 11/30 [00:03<00:05,  3.22it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 40%|████████████████████████████████▊                                                 | 12/30 [00:04<00:05,  3.24it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 43%|███████████████████████████████████▌                                              | 13/30 [00:04<00:05,  3.24it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 47%|██████████████████████████████████████▎                                           | 14/30 [00:04<00:04,  3.22it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 50%|█████████████████████████████████████████                                         | 15/30 [00:05<00:04,  3.24it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 53%|███████████████████████████████████████████▋                                      | 16/30 [00:05<00:04,  3.24it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 57%|██████████████████████████████████████████████▍                                   | 17/30 [00:05<00:03,  3.26it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 60%|█████████████████████████████████████████████████▏                                | 18/30 [00:06<00:03,  3.26it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 63%|███████████████████████████████████████████████████▉                              | 19/30 [00:06<00:03,  3.26it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 67%|██████████████████████████████████████████████████████▋                           | 20/30 [00:06<00:03,  3.26it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 70%|█████████████████████████████████████████████████████████▍                        | 21/30 [00:06<00:02,  3.24it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 73%|████████████████████████████████████████████████████████████▏                     | 22/30 [00:07<00:02,  3.25it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 77%|██████████████████████████████████████████████████████████████▊                   | 23/30 [00:07<00:02,  3.19it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 80%|█████████████████████████████████████████████████████████████████▌                | 24/30 [00:07<00:01,  3.15it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 83%|████████████████████████████████████████████████████████████████████▎             | 25/30 [00:08<00:01,  3.16it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 87%|███████████████████████████████████████████████████████████████████████           | 26/30 [00:08<00:01,  3.13it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 90%|█████████████████████████████████████████████████████████████████████████▊        | 27/30 [00:08<00:00,  3.12it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 93%|████████████████████████████████████████████████████████████████████████████▌     | 28/30 [00:09<00:00,  3.12it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
 97%|███████████████████████████████████████████████████████████████████████████████▎  | 29/30 [00:09<00:00,  3.08it/s]*** Error executing callback cfg_denoiser_callback for B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 85, in animatediff_on_cfg_denoiser
        ad_params.text_cond = ad_params.prompt_scheduler.multi_cond(cfg_params.text_cond, prompt_closed_loop)
    AttributeError: 'NoneType' object has no attribute 'multi_cond'

---
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:09<00:00,  3.05it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 30/30 [00:08<00:00,  3.09it/s]
Begin to load 1 model
Moving model(s) has taken 0.30 seconds
*** Error running postprocess_batch_list: B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\scripts.py", line 859, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py", line 79, in postprocess_batch_list
        params.prompt_scheduler.save_infotext_img(p)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'

---
*** Error running postprocess: B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "B:\2024AI\webui_forge_cu121_torch21\webui\modules\scripts.py", line 843, in postprocess
        script.postprocess(p, processed, *script_args)
      File "B:\2024AI\webui_forge_cu121_torch21\webui\extensions\sd-forge-animatediff\scripts\animatediff.py", line 84, in postprocess
        params.prompt_scheduler.save_infotext_txt(res)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:09<00:00,  3.03it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:09<00:00,  3.09it/s]

**Comment by continue-revolution** [comment]
@captainzero93 we no longer support hotshotxl in its original format. Try this one https://huggingface.co/conrevo/AnimateDiff-A1111/resolve/main/motion_module/mm_sdxl_hs.safetensors?download=true

**Comment by captainzero93** [comment]
@continue-revolution appriciate it, sorry for my oversight, maybe the readme just needs a quick update? Cheers

p[s: what about temporal diff ? and the others I don't see them there

**Comment by continue-revolution** [comment]
@captainzero93 other motion modules should be working like previous ones. I forgot to mention this in README and I will push an update later today.

motion lora is not working rn, i2i batch should be working later today or tomorrow. I may need some time to figure out the best way to do motion lora cuz I don't like ComfyUI's lora system

**Comment by KingTigh** [comment]
I'm having the exact same problem and have tried out nearly all available motion models, currently just trying to get this to work for SD1.5 no trying XL. error pops up at the start and before each generation when using control net with animatediff

**Comment by continue-revolution** [comment]
hopefully everything has been fixed right now. if not, let me know.

**Comment by Kaki-In** [comment]
I am still getting this exact issue, but I can't find how to fix it
I have tried changing models, using the exacts one of tutorials, etc... but nothing seems to work. 
How did you fixed it?
